blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions (ideas & Q&A)
    url: https://github.com/albertuszerk/frequency/discussions/categories/issues-ideas
    about: Start here for questions, ideas and open-ended discussions.
