name: Build Tailwind CSS

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '**/*.htm'
      - '**/*.html'
      - '**/*.js'
      - 'tailwind.config.js'
      - 'postcss.config.js'
      - 'src/tailwind.input.css'
      - 'package.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm install --no-audit --no-fund

      - name: Build CSS
        run: npm run build:css

      - name: Upload artifact (tailwind.min.css)
        uses: actions/upload-artifact@v4
        with:
          name: tailwind-css
          path: tailwind.min.css

      - name: Commit CSS back to repo (main)
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add tailwind.min.css
          git commit -m "chore: build tailwind.min.css [skip ci]" || echo "No changes"
          git push
